apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pet-store
  description:  |
    pet store api
spec:
  type: openapi
  owner: thbs
  lifecycle: production
  system: production
  definition:
    $text: https://github.com/baludeepak7/Demo/blob/main/openapi.yaml
